### ISSUE TITLE
Save checkpoint

### ISSUE THREAD

**Issue by thibaudart** [lllyasviel/ControlNet#221]
Hi

how can I save checkpoint without waiting a full epoch?

**Comment by tommy-qichang** [comment]
You can use ModelCheckpoint to set the saving steps rather than epochs.
for instance mine code is as followed:

`
from pytorch_lightning.callbacks import ModelCheckpoint

checkpoint_callback = ModelCheckpoint(every_n_train_steps=5000, save_last=True,  save_weights_only=False, filename='exp_sd21_{epoch:02d}_{step:06d}')`
