### ISSUE TITLE
SD 2.1 support, openpose

### ISSUE THREAD

**Issue by alfredplpl** [lllyasviel/ControlNet#43]
I would like to use the controlnet on SD 2.1 because I finetune SD2.1 .
My models, Picasso Diffusion and Cool Japan Diffusion, and Waifu Diffusion 1.5 are made of SD 2.1.
So, I cannot apply this method.

Please deal with SD 2.1.
Especially, I would like to use it conditioned  by Openpose data.
Or please give me idea for SD 2.1.

The reference image (Picasso Diffusion):
![9F8FBB7D-32E9-420F-9888-4EC8F3A34B94](https://user-images.githubusercontent.com/3625196/218733850-4c0bda7d-9f73-4e21-af05-e8ef4fc9176e.png)

**Comment by lllyasviel** [comment]
Hi alfredplpl,

Before we conduct the project, we did some research about SD1 vs SD2. Let us first do not consider Stable Diffusion itself, our conclusion is that, unfortunately, SD2’s text encoder does not outperform OpenAI CLIP.

Evidences are:

1. SD2’s text encoder is not peer reviewed work. We do not have enough evidence to say it outperform CLIP.

2. Stability recently shows some benchmarks with metrics to show that SD2’s text encoder is better, but these metrics may not generalize to all tasks. For example, 8 years ago, when a technique called “neural style transfer” is popular, the VGG19 is the best encoder; many models like resnet or densenet have better performance, but these model can not compete VGG19 in style transfer. SD2’s text encoder is facing the same problem.

4. We question can SD2’s text encoder reproduce some CLIP applications like https://kvfrans.com/clipdraw-exploring-text-to-drawing-synthesis/ and https://clipasso.github.io/clipasso/ and https://text2live.github.io/ . If not (which is actually somewhat likely), then SD2’s text encoder may have some essential problems.

Because of these, SD2’ text encoder has not been proved as technically solid to really help SD. SD2 may or may not be fine tuned to models as good as SOTA models. Although unfortunate, the community’s fine tuning efforts may be Stability’s social experiment to test their new encoder.

Beside, SD2’s seemly better default result may or may not be related their encoder. Their training is invisible for us and we do not know how the training is ended. We should also consider achieving good looking results in some topic is not difficult nowadays – community have lots of methods.

**Comment by FurkanGozukara** [comment]
@lllyasviel this is a gold information

ty for sharing

**Comment by alfredplpl** [comment]
Thank you for the insightful reply.
However, your model will cause more ethical problems.

I feel that SD2 text encoder is lesser than  SD1's one.
Especially, SD2 text encoder cannot deal with NSFW words.
As a result, SD 1.5 based models like Anything v3 are used for generating NSFW images.
Some SD 1.5 based models is based on the leaked Novel AI Diffusion.
According the developer's comment, Anything v3 is made of leaked Novel AI Diffusion model.
Many SD 1.5 based models are made of leaked Novel AI Diffusion model.
The models have potentials to commit a crime.

In fact, some users use the your model for generating NSFW content by leaked model. The attached image is one of the input images.

![Fm4feGmaUAEu9Tc](https://user-images.githubusercontent.com/3625196/218896710-8edf0adf-42ab-4615-ac23-67448dde8939.PNG)

My model, Picasso Diffusion, is not made of leaked Novel AI Diffusion model because I think the model have many problems.
Therefore, please rethink my opinion.

**Comment by lllyasviel** [comment]
We have plan to get official permission from Novel AI.

**Comment by alfredplpl** [comment]
I see. 

By the way, can we create ControlNet for SD 2.1 by this repository?

I will try to create ControlNet for SD 2.1.

**Comment by lllyasviel** [comment]
Added https://github.com/lllyasviel/ControlNet/commit/2a4424c1c0623d76592d2ef2f486c3de487ef4b5

**Comment by ProGamerGov** [comment]
Has anyone released a trained a 2.1 ControlNet yet?

**Comment by lllyasviel** [comment]
This issue is deleted upon some external requests
