### ISSUE TITLE
Larger dataset for training control-net

### ISSUE THREAD

**Issue by yinkangning0124** [lllyasviel/ControlNet#442]
Dear ControlNet team,
We know the initial intention of ControlNet is to use small dataset to finetune the original model. However, if the dataset of training ControlNet is larger than that of training the original model, is there any changes I have to make comparing to the classical training process of ControlNet? Thanks a lot !!!

Kangning.

**Comment by geroldmeisinger** [comment]
The original Stable Diffusion 1.5 base model was trained on 5B+ images. You want to train a control net on more than 5B images?
You might run into an overfitting problem, see here:
[Uncanny Faces tutorial](https://huggingface.co/blog/train-your-controlnet): _"We trained the model for 3 epochs (this means that the batch of 100K images were shown to the model 3 times) and a batch size of 4 (each step shows 4 images to the model). This turned out to be excessive and overfit (so it forgot concepts that diverge a bit of a real face, so for example "shrek" or "a cat" in the prompt would not make a shrek or a cat but rather a person, and also started to ignore styles)."_

Although the original canny model was trained on 3M images https://arxiv.org/abs/2302.05543 and than training was resumed in ControlNet 1.1 https://github.com/lllyasviel/ControlNet-v1-1-nightly#controlnet-11-canny without running into overfitting.

~~I don't understand why canndy edge model is not overfitting? Maybe they dropped enough prompts and randomized the canndy edge parameters enough.~~

**Comment by geroldmeisinger** [comment]
https://arxiv.org/abs/2302.05543v1 (note V1)
_"In this case, since the risk of over-fitting is relatively low, we can first train ControlNets for a large enough number of iterations (usually more than 50k steps), and then unlock all weights of the Stable Diffusion and jointly train the entire model as a whole. This would lead to a more problem-specific model."_
